### PR TITLE
Add PA scraper (WIP)

### LINKED ISSUE #374: Add PA scraper
Multiple HTML pages, line break delimited: https://www.dli.pa.gov/Individuals/Workforce-Development/warn/notices/Pages/default.aspx

### PR DESCRIPTION
**Pull request by chriszs**
Add scraper for Pennsylvania.

## Steps to test
```sh
python -m warn.cli PA
```

Closes #374

### CODE REVIEW

**Comment by chriszs** [comment]
Closing until I can get back to this, hopefully soon.

**Comment by chriszs** [comment]
Pulling this one back out as I've gotten it mostly working. Still a bunch of small errors from inconsistent formatting to deal with, but it's close.

**Comment by chriszs** [comment]
Closing for now.

**Comment by Ash1R** [comment]
Switching the function to write_rows_to_csv and dicts to lists helps. The layoff date and layoff type are switched after a certain month, so fixing that should solve all the problems.

**Pull request closed without merging**
