### PR TITLE
Cut to the Action

### LINKED ISSUE #414: CI takes makes longer than it needs to
CI takes about 5 minutes. Roughly 4 of those minutes appear to be Python/pipenv setup (2 minutes per step). I switched to the official Python setup action with built in catching over on the bot repo and it now takes 7 seconds (so about 14 seconds total, maybe).

Why is this important? Because when you get CI feedback on builds faster, you can iterate on PRs much faster.

This is how I did it:
```yaml
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pipenv'
      - run: pipenv install
```

### PR DESCRIPTION
**Pull request by chriszs**
Speeds up CI by using official Python setup action, built in caching. I did have to upgrade to Python 3.8 to get this to work for reasons I'm not entirely clear on (assume the action doesn't bundle 3.7?). But it does cut the CI time down to 2 minutes, which is about 3 minutes faster than it was and 1 minute slower than I was hoping.

Closes #414

### CODE REVIEW

**Comment by chriszs** [comment]
Okay, I did have to upgrade to Python 3.8 to get this to work for reasons I'm not entirely clear on (assume the action doesn't bundle 3.7?). But it does cut the CI time down to 2 minutes, which is about 3 minutes faster than it was and 1 minute slower than I was hoping.

**Comment by palewire** [comment]
Right now we have to stick with 3.7 due to some downstream deployment issues.

**Comment by chriszs** [comment]
Got it. It does still test in 3.7 during the matrix phase, it just lints, static type checks, tests doc generation, builds and releases in 3.8. I don't know if that matters or not.

**Comment by palewire** [comment]
This new python action feature, with the cache built in, is great. Let's use it. Thank you!

**Pull request merged**
