### PR TITLE
Add IL Excel scraper

### LINKED ISSUE #81: Add IL scrape
https://www.illinoisworknet.com/LayoffRecovery/Pages/ArchivedWARNReports.aspx

May not be able to do this one. The PDF's have inconsistent structures within and the more recent files are excel files.

### PR DESCRIPTION
**Pull request by chriszs**
Add Excel-only scraper for IL. Also downloads PDFs, contains skeleton code to parse them.

## Steps to test
```sh
python -m warn.cli IL -l DEBUG
```

Closes #81.

### CODE REVIEW

**Comment by chriszs** [comment]
Current errata:
- [ ] To simplify this I'm only supporting PDFs from 2004 onward currently since those have nice clean tables. There are a couple in 2003 that have the same sorts of tables that we could parse, but doing a year cutoff is simpler. Not out of the question earlier PDF reports could be parseable, just slightly trickier.
- [ ] The [Jan. 2019 report](https://www.illinoisworknet.com/DownloadPrint/January%202019%20Monthly%20WARN%20Report.pdf) is the lone scanned document, uncertain whether and how to support that yet.
- [ ] There are "supplemental" (e.g. amendment) reports in less-structured text at the end of the PDFs, which I don't yet support but plan to before this lands. I do include those when they're in the Excel files.
- [ ] In some cases I may not be including the second line of addresses from PDFs. That I plan to fix.
- [ ] There are two errant or partial column names I'm picking up from somewhere. Definitely needs to be fixed.

**Comment by chriszs** [comment]
Going to try to add OCR to this one. It's overkill for one older document, but I know of at least one other state where we'd need it. Will be interesting to see how pdfplumber performs on it, it's explicitly not optimized for that (but could work anyway).

**Comment by chriszs** [comment]
Bringing this one back out and commenting out PDF parsing until the issues above can be addressed (though it still downloads some PDFs and the PDF parsing code is still in there as a skeleton for anyone who follows). Excel gets us the last two years.

**Comment by palewire** [comment]
If I understand you right, you're propose merging and Excel only scraper to start? If that's right, can we cut out the PDF logic from this patch? I know it's a hassle, but it will allow for a cleaner interim merge.

**Comment by chriszs** [comment]
Removed the PDF parsing code.

**Comment by palewire** [comment]
This is merged. Thank you!

**Pull request merged**
